# /etc/zabbix/zabbix_agent2.d/proxmox-raid-smart.conf
UserParameter=raid.pd.discovery,sudo /usr/local/bin/proxmox_raid_pd_attr.sh discover /dev/sda
UserParameter=raid.pd.type[*],sudo /usr/local/bin/proxmox_raid_pd_attr.sh type /dev/sda "$1"
UserParameter=raid.pd.health.raw[*],sudo /usr/local/bin/proxmox_raid_pd_attr.sh health /dev/sda "$1"
UserParameter=raid.pd.health[*],sudo /usr/local/bin/proxmox_raid_pd_attr.sh health /dev/sda "$1"
UserParameter=raid.pd.wear[*],sudo /usr/local/bin/proxmox_raid_pd_attr.sh wear /dev/sda "$1"
UserParameter=raid.pd.wear.pct[*],sudo /usr/local/bin/proxmox_raid_pd_attr.sh wearpct /dev/sda "$1"
UserParameter=raid.pd.dynamic.status[*],sudo /usr/local/bin/proxmox_raid_pd_attr.sh dynamic /dev/sda "$1"
