# This is a configuration file for Zabbix agent 2 (Unix)
# Edited for Proxmox host pmx3-colocity-mohakhali and Zabbix server 10.9.0.68

############ GENERAL PARAMETERS #################

PidFile=/run/zabbix/zabbix_agent2.pid

LogFile=/var/log/zabbix/zabbix_agent2.log
LogFileSize=0

##### Passive checks related

Server= "zabbix machine ip"

##### Active checks related

ServerActive="zabbix machine ip"
Hostname=

############ ADVANCED PARAMETERS #################

Timeout=15

####### USER-DEFINED MONITORED PARAMETERS #######

ControlSocket=/run/zabbix/agent.sock

####### TLS-RELATED PARAMETERS #######
# Keep unencrypted for now unless you decide to enable PSK later.
# TLSConnect=unencrypted
# TLSAccept=unencrypted

####### ITEM KEY RESTRICTIONS #######
# Order matters. Allow the keys we need, then deny everything else.
AllowKey=system.run[*]
AllowKey=proxmox.raid.pd.discovery
AllowKey=proxmox.raid.pd.dynamic.status[*]
AllowKey=proxmox.raid.pd.health.raw[*]
AllowKey=proxmox.raid.pd.health[*]
AllowKey=proxmox.raid.pd.type[*]
AllowKey=proxmox.raid.pd.wear.pct[*]
AllowKey=proxmox.raid.pd.wear[*]
DenyKey=*


### Includes
Include=./zabbix_agent2.d/plugins.d/*.conf
Include=/etc/zabbix/zabbix_agent2.d/*.conf
